development:
  adapter: postgresql
  database: baker_app_development
  username: ajay
  password:
  host: localhost
  pool: 5

test:
  adapter: postgresql
  database: baker_app_test
  username: ajay
  password:
  host: localhost
  pool: 5

production:
  adapter: postgresql
  database: baker_app_production
  username: ajay
  password:
  host: localhost
  pool: 5
